//To Do
//make
//generate multiple descriptions at once - appearance - dont with regular gpt
//for each appearance generate images - responses api
//for each image track the convo with the response id
//makes revision prompts easier
//allow file upload if file present attach it to responses api






//generate locations/characters
//save
//canvas dimensions - sets after effects, and image
//move all data to uploaded data - staging, rename previews/images
//options to choose input fidelity and image size, quality
//use same upload file logic across app
//make all upload images use the same function - ensure it deletes similar named files.
//ensure proper schema tables and types are synced - many many
//space with uuid all upload values that are referenced by another id - project id, character id...etc projectId____uuid - then split it to delete correct file.
//take time and validate - all charactersInProject use aactive appreacance id as starting values only, that scene values are unique to each scene (appearance, location). Same with locationsInProject
//enetually return extra data in response
//make save on client




//Ideas
//long term - 3d game




//Notes
//remember to sync env variables

//naming
//schema - plural
//type - singular with Type added - e.g userType
//serverFunctions - handlePlural e.g handleUsers - singular function names - e.g addUser - getAll remains plural - e.g getUsers
//api routes - container name first - then verb. e.g projects - download, files - upload
//generate apeparance description
//auto upload image




//To Do completed
//project default values setter...
//set art style at project layer - water color, strong lines...
//remove prompt set at start, make default - addedit projects...
//each scene has visual instructions - dont worry about appearance, just what the characters are doing in a given scene. e.g max standing off to the side, kim talking
//set prompt for visual appearance...
//test it works...
//generate locations in db...
//every location has a name, description and views e.g max house...
//each view has a name (e.g front door, bedroom), reference image and locationVariationName: e.g summer house, winter house...
//locations - server action..., add edit..., view...
//then if edit an image - user upload edited image along with prompt - temp dir...
//user generate image prompt...
//user edit image from file uploaded...
//allow user to make image/edit from prompt...
//find way to pass reference images to this generation...
//project has characterToProjects - each has active appearance...
//each scene still keeps track of the appearance of all users in it - appareanceObj...
//ensure feature props passed down match...
//change the way we choose active appearance starter - put on charactersToProjects...
//same as projects to characters - same fetch extra on default...
//import locationsInProject...
//location selector for project - need location to projects db...
//show active location - with setter...
//verify seeing active location...
//update story - prompt...
//story essentially has free reign to make a story given the current location context into all available locations...
//ensure add manual scene chooses a location (from active location) then a random view...
//maybe add activeView to locationsInProject...
//allow changing of these values - locationId, viewId...
//each scene has a location and viewId - if location not found set, if view not found set...
//have active location (stored on project) - views in each location - story maker aware of active location and can choose - udate prompt...
//dynamically chooses the best scenes for story progression...
//locations main dir - remake to read files from project...
//build out view selector for each locationInProject - viewProject area...
//build out view selector for each view in location...
//each scene sends up the view's reference image...
//if not seeing view set as default - each location needs at least 1 view...
//if not seeing location show setter...
//make forest: entrance, deep, oasis, exit...
//each character has active appearance along with defining description. upload that and reference images (view/character) along with visual instructions from scene - remove the condenser...
//same way to change location on projectsToLocations...
//make prompts on addedit character/location editable - make add variables to prompt in utility...
//fix objwithFile bug - still validates deleted array - dont allow delete if invalid...
//refine image preview gpt with central generation, multi context from options - uploading reference images...
//fix add edit character with form obj error check...
//each scene has characters in scene - active to depict - use this to determine active appearance check - not sure...
//natively have chracters for scene...
//move generate scene backgrounds to api...
//change scene character appearance to apperance...
//location variation names - ensure views choose active values...