import type { Metadata } from "next";
import "./globals.css";
import { Raleway, Manrope, Roboto, Rubik } from "next/font/google"
import { Toaster } from "react-hot-toast";
import localFont from "next/font/local";
import { auth } from "@/auth/auth";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/navbar/Navbar";

const roboto = Roboto({
  variable: "--roboto",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--raleway",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--manrope",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--rubik",
  subsets: ["latin"],
});

const materialSymbolsOutlined = localFont({
  src: "./fonts/MaterialSymbolsOutlined-VariableFont_FILL,GRAD,opsz,wght.ttf",
  variable: "--materialSymbolsOutlined",
});
const materialSymbolsRounded = localFont({
  src: "./fonts/MaterialSymbolsRounded-VariableFont_FILL,GRAD,opsz,wght.ttf",
  variable: "--materialSymbolsRounded",
});
const materialSymbolsSharp = localFont({
  src: "./fonts/MaterialSymbolsSharp-VariableFont_FILL,GRAD,opsz,wght.ttf",
  variable: "--materialSymbolsSharp",
});

export const metadata: Metadata = {
  title: "Story Maker",
  description: "Generated by max",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()

  return (
    <html lang="en">
      <body className={`${raleway.variable} ${manrope.variable} ${roboto.variable} ${rubik.variable} ${materialSymbolsOutlined.variable} ${materialSymbolsRounded.variable} ${materialSymbolsSharp.variable} antialiased`}>
        <SessionProvider session={session}>
          <Toaster position="top-center" reverseOrder={false} />
          <Navbar
            menuInfoArr={[
              {
                title: "characters",
                link: "/characters",
              },
              {
                title: "emotions",
                link: "/emotions",
              },
              {
                title: "tags",
                link: "/tags",
              },
            ]}
          />

          {children}
        </SessionProvider>
      </body>
    </html>
  );
}